### PR TITLE
Update for symfony 5

### PR DESCRIPTION
**Pull request by ivan1986**
Fix tree builder and twig
update composer
update travis config
update libs

### CODE REVIEW

**Comment by DjLeChuck** [comment]
Hi,

Any news on this? Is there something missing on which we can help?

**Comment by ivan1986** [comment]
yes, what also need?
it's good point for update version - 3.x is unsuported soon

**Comment by ivan1986** [comment]
@wtfzdotnet @MarkRedeman ping
any news?
can you merge?

**Comment by wtfzdotnet** [comment]
If for time being you can live on the edge on `dev-master`, I think we need some more changes, just set up a test project and working my way around some changes. Sorry for the delay! :)

**Comment by ivan1986** [comment]
Cool, thanks

**Comment by wtfzdotnet** [comment]
As  far as I can see right now;

- DoctrineCacheBundle is being deprecated so caching has to be moved elsewhere
- Services need to adhere to classes now; to not give everyone a headache with a bigger application I'm adding a compiler pass that adds aliases for the old ones, so you can migrate over time.

If I might miss anything, let me know.

**Comment by wtfzdotnet** [comment]
Been working some more on this after work today, however this has implications for the library underneath as well.

Given the code is practically 6-7 years old, it needs a little retouching, and given new dependency versions, it has conflicting interface implementations which should be resolved. Given those facts I am going to try and work on a major update for `php-tmdb/api` aswell as `php-tmdb/symfony`. This should include the following list I've put together so far;

- (Re-Implementation) of PSR-3
- Implementation of PSR-7
- Implementation of PSR-12
- Implementation of PSR-14
- Implementation of PSR-16
- Implementation of PSR-17
- Implementation of PSR-18
- Cleanup of tests
- Dropping doctrine cache ( bring your own PSR-16 client )
- Dropping guzzle http ( bring your own PSR-18 client )
- New CI/CD integration ( github actions, as travis-ci is being abandoned )
    - Code style checking
    - Unit tests running on PHP 7.3, 7.4 and 8.0 ( still allowing failures as of now )

As you might have noticed I am quite the busy man, I cannot guarantee when the next stable version will hit, but I intend to make a release that will last for a few years again, and hopefully with improved test suites on both side, will make it less painful to just merge stuff without testing much.

@ivan1986 if you are interested in helping out, I would gladly appreciate it. Just need to lay down the groundwork first, and see which direction to steer in.

**Comment by ivan1986** [comment]
ok, i want update my project form sf4 to sf5 on weekend and try to fix all which i find

**Comment by wtfzdotnet** [comment]
I just opened up https://github.com/php-tmdb/symfony/pull/29, make sure to branch off from there. It's the work I started the other day, so far from finished, but open up pr's against it as you wish.

**Comment by ivan1986** [comment]
hm, for my project all works fine
i load films and shows info, cache works, because also exist doctrine
i not expected this - no issues on update to last versions of all packages

**Comment by wtfzdotnet** [comment]
As soon deprecations are going to be "permanent", this thing will be broken :-). I'll keep working on retouching things, just finishing off my night trying to get all the github action hooks going I can use for all php-tmdb projects.

**Pull request merged**
